Implement Base Architecture of converter
ProtoPie/remora-figma-plugin pull request #4
Opened 2024-01-22 09:41 UTC by Tom0Kim

### [Summary]
- Converter Exporter 기본 구조 구현

### [Check List]
- 파일 구성
- 폴더 구조
- etc

### [Description]
- 아래 코드에 작성

2024-01-22 09:42 UTC, Tom0Kim commented on App/src/figma/constants.ts
> +export const PLUGIN_ID_PREFIX = 'FigmaPlugin:';
converter, exporter 내부에서 공통적으로 사용하는 상수 리스트

2024-01-22 09:42 UTC, Tom0Kim commented on App/src/figma/converter/Converter.ts
> +import { FigmaUtil } from "../util";
Figma model -> Pie model converting 작업을 하는 Base 클래스

2024-01-22 09:44 UTC, Tom0Kim commented on App/src/figma/converter/FrameNodeConverter.ts
> +import { FigmaUtil } from "../util";
실제로 Figma FrameNode 타입을 Pie modeling 하는 클래스

2024-01-22 09:44 UTC, Tom0Kim commented on App/src/figma/exporter/Exporter.ts
> +import { Converter } from "../converter/Converter"
유저가 선택한 figma node에 대한 converting 작업을 완료하고, 외부(아마 protopie Cloud로 예상)로 전달 하기 위한 클래스

2024-01-22 09:45 UTC, Tom0Kim commented on App/src/figma/type.ts
> +export type ContainerNode = FrameNode | GroupNode | ComponentNode | InstanceNode;
converter, exporter 내부에서 공통적으로 사용하는 타입 리스트

2024-01-22 09:45 UTC, Tom0Kim commented on App/src/figma/util.ts
> +import { PLUGIN_ID_PREFIX } from "./constants";
converter, exporter 내부에서 공통적으로 사용하는 유틸 클래스

2024-01-22 09:46 UTC, Tom0Kim commented on App/tsconfig.json
> +    "typeRoots": ["./node_modules/@types", "./node_modules/@figma"],
전역에서 figma object, figma type에 대한 내용을 접근하기 위해 작성

2024-01-23 05:44 UTC, steve220829 requested changes

2024-01-23 05:58 UTC, Tom0Kim commented on App/src/figma/util.ts
> +  return node.type === 'FRAME' || node.type === 'GROUP' || node.type === 'COMPONENT' || node.type === 'INSTANCE';
네 안되는 것 같습니다..
`'ContainerNode' only refers to a type, but is being used as a value here.ts(2693)`

2024-01-23 06:12 UTC, Tom0Kim commented on App/src/figma/exporter/Exporter.ts
> +}
@steve220829 

네 맞습니다. 저도 비슷하게 생각하고 있었습니다. 좋은 리뷰 감사드립니다.

추가적으로 생성되는 Exporter들(e.g FileExporter, SocketIOExporter)은 추후에 실제로 해당 작업 들어 갈 때 구현하면 좋을 것 같습니다. :)
현 PR 코드에 대한 목적은 아마 "추가적으로 생성되는 exporter들을 현재 구조에서 Factory pattern 으로 구현이 가능한가?"에 대한 아키텍처 검증 단계라 생각됩니다..!

2024-01-23 08:34 UTC, steve220829 commented
코드 Lint 할수 있게 넣어 주세요.

2024-01-23 08:34 UTC, steve220829 approved these changes

2024-01-23 08:58 UTC, Tom0Kim commented
> 코드 Lint 할수 있게 넣어 주세요.

혹시 프로젝트에 Lint 적용하는 것을 말씀하신걸까요? 그런거라면 이미 적용되어 있습니다. 
![image](https://github.com/ProtoPie/remora-figma-plugin/assets/155513036/01d6280f-e021-4068-95b3-1d448af71f3e)

2024-01-23 09:46 UTC, merged